
Vagrant.configure("2") do |config|

  # the basebox to use
  config.vm.box = "boxcutter/ubuntu1604"
  config.vm.box_version = "2.0.26"

  # virtualbox specific customizations
  config.vm.provider "virtualbox" do |vbox, override|
    vbox.customize ["modifyvm", :id,
      "--name", "Etka Demo",
      "--memory", 1024,
      "--cpus", 4
    ]
  end

  # set the hostname
  config.vm.hostname = "etka-demo"

  # run a shell provisioner
  config.vm.provision "shell", inline: <<-EOF
    sudo apt-get install cowsay -y
    /usr/games/cowsay "hello etka!"
  EOF

end
